#%%
import base64
import matplotlib.pyplot as plt
import numpy as np
import json
from ast import literal_eval

data1encoded = 'W3sic3RhcnRUaW1lIjoxNjE4NTE4MzA3MzkwLCJkdXJhdGlvbiI6MTM2NzcsInNjb3JlIjo0LCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE0MTQsInBpcGVoZWlnaHQiOjkwLjksImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTgzMjY4OTYsImR1cmF0aW9uIjoxMDkxNiwic2NvcmUiOjIsImdyYXZpdHkiOjAuMjUsInBpcGVJbnRlcnZhbCI6MTQ0Mi4yOCwicGlwZWhlaWdodCI6OTIuNzE4LCJjb2xsaXNpb25Qb3NpdGlvbiI6MTF9LHsic3RhcnRUaW1lIjoxNjE4NTE4MzQyMDk2LCJkdXJhdGlvbiI6MTUwMDIsInNjb3JlIjo1LCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE0ODUuNTQ4NCwicGlwZWhlaWdodCI6OTUuNDk5NTQwMDAwMDAwMDEsImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTgzNjE1OTcsImR1cmF0aW9uIjo0MDM3MSwic2NvcmUiOjIyLCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE0ODUuNTQ4NCwicGlwZWhlaWdodCI6OTUuNDk5NTQwMDAwMDAwMDEsImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTg0MTMyMjAsImR1cmF0aW9uIjoyMjk3OCwic2NvcmUiOjEwLCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE0ODUuNTQ4NCwicGlwZWhlaWdodCI6OTUuNDk5NTQwMDAwMDAwMDEsImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTg0NDAxNzMsImR1cmF0aW9uIjo0NjY5Mywic2NvcmUiOjI2LCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE0ODUuNTQ4NCwicGlwZWhlaWdodCI6OTUuNDk5NTQwMDAwMDAwMDEsImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTg0OTMzODYsImR1cmF0aW9uIjoyNjkwMSwic2NvcmUiOjEzLCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE0ODUuNTQ4NCwicGlwZWhlaWdodCI6OTUuNDk5NTQwMDAwMDAwMDEsImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTg1MjY0MDUsImR1cmF0aW9uIjoxODIyOSwic2NvcmUiOjcsImdyYXZpdHkiOjAuMjUsInBpcGVJbnRlcnZhbCI6MTU0NC45NzAzMzU5OTk5OTk5LCJwaXBlaGVpZ2h0Ijo5OS4zMTk1MjE2MDAwMDAwMiwiY29sbGlzaW9uUG9zaXRpb24iOjExfSx7InN0YXJ0VGltZSI6MTYxODUxODU2OTMyNywiZHVyYXRpb24iOjcxMjIzLCJzY29yZSI6NDEsImdyYXZpdHkiOjAuMjUsInBpcGVJbnRlcnZhbCI6MTU5MS4zMTk0NDYwNzk5OTk4LCJwaXBlaGVpZ2h0IjoxMDIuMjk5MTA3MjQ4MDAwMDEsImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTg2NjUyNTksImR1cmF0aW9uIjo0NzQ5MSwic2NvcmUiOjI1LCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE1OTEuMzE5NDQ2MDc5OTk5OCwicGlwZWhlaWdodCI6MTAyLjI5OTEwNzI0ODAwMDAxLCJjb2xsaXNpb25Qb3NpdGlvbiI6MTF9XQ=='
data1bytes = base64.b64decode(data1encoded)
data1 = literal_eval(data1bytes.decode('utf8'))

data2encoded = 'W3sic3RhcnRUaW1lIjoxNjE4NTE4ODk2MzYzLCJkdXJhdGlvbiI6ODA5Miwic2NvcmUiOjAsImdyYXZpdHkiOjAuMjUsInBpcGVJbnRlcnZhbCI6MTQxNCwicGlwZWhlaWdodCI6OTAuOSwiY29sbGlzaW9uUG9zaXRpb24iOjExfSx7InN0YXJ0VGltZSI6MTYxODUxODkwOTU3NSwiZHVyYXRpb24iOjEzNjIwLCJzY29yZSI6NCwiZ3Jhdml0eSI6MC4yNSwicGlwZUludGVydmFsIjoxNDQyLjI4LCJwaXBlaGVpZ2h0Ijo5Mi43MTgsImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTg5MzAzMDgsImR1cmF0aW9uIjoxMzI3NCwic2NvcmUiOjQsImdyYXZpdHkiOjAuMjUsInBpcGVJbnRlcnZhbCI6MTQ4NS41NDg0LCJwaXBlaGVpZ2h0Ijo5NS40OTk1NDAwMDAwMDAwMSwiY29sbGlzaW9uUG9zaXRpb24iOjExfSx7InN0YXJ0VGltZSI6MTYxODUxODk0Nzc1NSwiZHVyYXRpb24iOjM3NDkzLCJzY29yZSI6MjAsImdyYXZpdHkiOjAuMjUsInBpcGVJbnRlcnZhbCI6MTQ4NS41NDg0LCJwaXBlaGVpZ2h0Ijo5NS40OTk1NDAwMDAwMDAwMSwiY29sbGlzaW9uUG9zaXRpb24iOjExfSx7InN0YXJ0VGltZSI6MTYxODUxODk4OTUxNSwiZHVyYXRpb24iOjcxNTIzLCJzY29yZSI6NDMsImdyYXZpdHkiOjAuMjUsInBpcGVJbnRlcnZhbCI6MTUxNS4yNTkzNjgsInBpcGVoZWlnaHQiOjk3LjQwOTUzMDgwMDAwMDAxLCJjb2xsaXNpb25Qb3NpdGlvbiI6MTF9LHsic3RhcnRUaW1lIjoxNjE4NTE5MDY1MTkyLCJkdXJhdGlvbiI6NjcyODcsInNjb3JlIjozOSwiZ3Jhdml0eSI6MC4yNSwicGlwZUludGVydmFsIjoxNTMwLjQxMTk2MTY4LCJwaXBlaGVpZ2h0Ijo5OC4zODM2MjYxMDgwMDAwMiwiY29sbGlzaW9uUG9zaXRpb24iOjExfSx7InN0YXJ0VGltZSI6MTYxODUxOTEzNzI5MSwiZHVyYXRpb24iOjgyNDMsInNjb3JlIjowLCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE1NjEuMDIwMjAwOTEzNiwicGlwZWhlaWdodCI6MTAwLjM1MTI5ODYzMDE2MDAyLCJjb2xsaXNpb25Qb3NpdGlvbiI6MTF9LHsic3RhcnRUaW1lIjoxNjE4NTE5MTQ5Njk0LCJkdXJhdGlvbiI6NDcwMTIsInNjb3JlIjoyNSwiZ3Jhdml0eSI6MC4yNSwicGlwZUludGVydmFsIjoxNTYxLjAyMDIwMDkxMzYsInBpcGVoZWlnaHQiOjEwMC4zNTEyOTg2MzAxNjAwMiwiY29sbGlzaW9uUG9zaXRpb24iOjExfSx7InN0YXJ0VGltZSI6MTYxODUxOTIyMjY4OSwiZHVyYXRpb24iOjQ3Njk5LCJzY29yZSI6MjYsImdyYXZpdHkiOjAuMjUsInBpcGVJbnRlcnZhbCI6MTU2MS4wMjAyMDA5MTM2LCJwaXBlaGVpZ2h0IjoxMDAuMzUxMjk4NjMwMTYwMDIsImNvbGxpc2lvblBvc2l0aW9uIjoxMn0seyJzdGFydFRpbWUiOjE2MTg1MTkyNzQ3MzksImR1cmF0aW9uIjoxODYxMiwic2NvcmUiOjcsImdyYXZpdHkiOjAuMjUsInBpcGVJbnRlcnZhbCI6MTYwNy44NTA4MDY5NDEwMDgyLCJwaXBlaGVpZ2h0IjoxMDMuMzYxODM3NTg5MDY0ODIsImNvbGxpc2lvblBvc2l0aW9uIjoxMX1d'
data2bytes = base64.b64decode(data2encoded)
data2 = literal_eval(data2bytes.decode('utf8'))

data3encoded = 'W3sic3RhcnRUaW1lIjoxNjE4NTE5NjE5OTIwLCJkdXJhdGlvbiI6MTAyNDQsInNjb3JlIjoyLCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE0MTQsInBpcGVoZWlnaHQiOjkwLjksImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTk2MzQxNDgsImR1cmF0aW9uIjoyMTY2OCwic2NvcmUiOjEwLCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE0MTQsInBpcGVoZWlnaHQiOjkwLjksImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTk2NTk4OTEsImR1cmF0aW9uIjoxNTA2MSwic2NvcmUiOjUsImdyYXZpdHkiOjAuMjUsInBpcGVJbnRlcnZhbCI6MTQ0Mi4yOCwicGlwZWhlaWdodCI6OTIuNzE4LCJjb2xsaXNpb25Qb3NpdGlvbiI6MTF9LHsic3RhcnRUaW1lIjoxNjE4NTE5NjgyNjA0LCJkdXJhdGlvbiI6MTMzODQsInNjb3JlIjo0LCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE0ODUuNTQ4NCwicGlwZWhlaWdodCI6OTUuNDk5NTQwMDAwMDAwMDEsImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTk2OTk0NTYsImR1cmF0aW9uIjozMDQwNiwic2NvcmUiOjE1LCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE0ODUuNTQ4NCwicGlwZWhlaWdodCI6OTUuNDk5NTQwMDAwMDAwMDEsImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTk3MzM4MDEsImR1cmF0aW9uIjozNzIyMywic2NvcmUiOjIwLCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE0ODUuNTQ4NCwicGlwZWhlaWdodCI6OTUuNDk5NTQwMDAwMDAwMDEsImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTk3NzUxMTIsImR1cmF0aW9uIjo4MTgxLCJzY29yZSI6MCwiZ3Jhdml0eSI6MC4yNSwicGlwZUludGVydmFsIjoxNTQ0Ljk3MDMzNTk5OTk5OTksInBpcGVoZWlnaHQiOjk5LjMxOTUyMTYwMDAwMDAyLCJjb2xsaXNpb25Qb3NpdGlvbiI6MTF9LHsic3RhcnRUaW1lIjoxNjE4NTE5Nzg3MjU3LCJkdXJhdGlvbiI6ODIxODcsInNjb3JlIjo0OCwiZ3Jhdml0eSI6MC4yNSwicGlwZUludGVydmFsIjoxNTkxLjMxOTQ0NjA3OTk5OTgsInBpcGVoZWlnaHQiOjEwMi4yOTkxMDcyNDgwMDAwMSwiY29sbGlzaW9uUG9zaXRpb24iOjExfSx7InN0YXJ0VGltZSI6MTYxODUxOTg3Mzg2MiwiZHVyYXRpb24iOjI2OTAwLCJzY29yZSI6MTIsImdyYXZpdHkiOjAuMjUsInBpcGVJbnRlcnZhbCI6MTU5MS4zMTk0NDYwNzk5OTk4LCJwaXBlaGVpZ2h0IjoxMDIuMjk5MTA3MjQ4MDAwMDEsImNvbGxpc2lvblBvc2l0aW9uIjoxMX0seyJzdGFydFRpbWUiOjE2MTg1MTk5MDQ4MDMsImR1cmF0aW9uIjo2MTc1MSwic2NvcmUiOjM0LCJncmF2aXR5IjowLjI1LCJwaXBlSW50ZXJ2YWwiOjE2MjMuMTQ1ODM1MDAxNTk5OCwicGlwZWhlaWdodCI6MTA0LjM0NTA4OTM5Mjk2MDAyLCJjb2xsaXNpb25Qb3NpdGlvbiI6MTF9XQ=='
data3bytes = base64.b64decode(data3encoded)
data3 = literal_eval(data3bytes.decode('utf8'))

scores1 = []
gravity1 = []
pipeInterval1 = []
pipeHeight1 = []
for data in data1:
    scores1.append(data['score'])
    gravity1.append(data['gravity'])
    pipeInterval1.append(data['pipeInterval'])
    pipeHeight1.append(data['pipeheight'])

scores2 = []
gravity2 = []
pipeInterval2 = []
pipeHeight2 = []
for data in data2:
    scores2.append(data['score'])
    gravity2.append(data['gravity'])
    pipeInterval2.append(data['pipeInterval'])
    pipeHeight2.append(data['pipeheight'])

scores3 = []
gravity3 = []
pipeInterval3 = []
pipeHeight3 = []
for data in data3:
    scores3.append(data['score'])
    gravity3.append(data['gravity'])
    pipeInterval3.append(data['pipeInterval'])
    pipeHeight3.append(data['pipeheight'])

x = np.arange(1, 11, 1)

fig, ax = plt.subplots()  # Create a figure containing a single axes.
ax.plot(x, scores1[:10], label='player1')
ax.plot(x, scores2[:10], label='player2')
ax.plot(x, scores3[:10], label='player3')

plt.xticks(x)
ax.set_xlabel('Playthrough')
ax.set_ylabel('Score')
ax.set_title('Scores over 10 playthroughs')
ax.legend()

fig2, ax2 = plt.subplots()  # Create a figure containing a single axes.
ax2.plot(x, gravity1[:10], label='player1')
ax2.plot(x, gravity2[:10], label='player2')
ax2.plot(x, gravity3[:10], label='player3')

plt.xticks(x)
ax2.set_xlabel('Playthrough')
ax2.set_ylabel('Gravity')
ax2.set_title('Gravity strength over 10 playthroughs')
ax2.legend()

fig3, ax3 = plt.subplots()  # Create a figure containing a single axes.
ax3.plot(x, pipeInterval1[:10], label='player1')
ax3.plot(x, pipeInterval2[:10], label='player2')
ax3.plot(x, pipeInterval3[:10], label='player3')

plt.xticks(x)
ax3.set_xlabel('Playthrough')
ax3.set_ylabel('Pipe Interval Distance')
ax3.set_title('Pipe interval distance over 10 playthroughs')
ax3.legend()

fig4, ax4 = plt.subplots()  # Create a figure containing a single axes.
ax4.plot(x, pipeHeight1[:10], label='player1')
ax4.plot(x, pipeHeight2[:10], label='player2')
ax4.plot(x, pipeHeight3[:10], label='player3')

plt.xticks(x)
ax4.set_xlabel('Playthrough')
ax4.set_ylabel('Pipe Height')
ax4.set_title('Pipe height over 10 playthroughs')
ax4.legend()
# %%